### ISSUE TITLE
[JUnit] UI test failed

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1078]
### What happened ?

This build error occurred: https://github.com/mytourbook/mytourbook/actions/runs/4783605264/jobs/8504082112#step:11:20111

When I run the test, it stops here

![image](https://user-images.githubusercontent.com/1283445/233945527-2d59e868-7e5d-456a-9216-e457a2f3d1b6.png)

### Version

current main branch

### System

Windows

**Comment by FJBDev** [comment]
When UI tests fail, I first go look at the screenshot uploaded to the build  [artifacts](https://github.com/mytourbook/mytourbook/suites/12433164231/artifacts/661725582) to get a good idea of where it was failing or "hanging up".

For yesterday's build, the screenshot gives a good clue

![image](https://user-images.githubusercontent.com/25235665/234135077-f4607f87-ba12-4174-9f3c-754e38a44cf5.png)

Because UI tests sometimes rely on internet, the response delay can vary and in this case, adding a `sleep` fixes the issue for cases when OWM takes several seconds to respond

I have fixed that in my [current PR](https://github.com/mytourbook/mytourbook/pull/1064) with [this commit](https://github.com/FJBDev/mytourbook/pull/118/commits/69e0635fa8cf3a9ac124577715d2c7aa46c61a29)

**Comment by FJBDev** [comment]
When UI tests fail, I first go look at the screenshot uploaded to the build  [artifacts](https://github.com/mytourbook/mytourbook/suites/12433164231/artifacts/661725582) to get a good idea of where it was failing or "hanging up".

For yesterday's build, the screenshot gives a good clue

![image](https://user-images.githubusercontent.com/25235665/234135077-f4607f87-ba12-4174-9f3c-754e38a44cf5.png)

Because UI tests sometimes rely on internet, the response delay can vary and in this case, adding a `sleep` fixes the issue for cases when OWM takes several seconds to respond

I have fixed that in my [current PR](https://github.com/mytourbook/mytourbook/pull/1064) with [this commit](https://github.com/FJBDev/mytourbook/pull/118/commits/69e0635fa8cf3a9ac124577715d2c7aa46c61a29)

**Comment by wolfgang-ch** [comment]
>For yesterday's build, the screenshot gives a good clue
I just implemented this progress dialog, otherwise you would see only a hourglass

During my testing of the new import UI, I often saw just this hourglass which is the reason why there is now a progress dialog

**Comment by wolfgang-ch** [comment]
> I am personally not a fan of those "gray old empty" dialogs that block the view but that might be just my preference

With this commit https://github.com/mytourbook/mytourbook/commit/74298d636ae3d88c50459d00ca4f5eb2fa3aa02f the progress dialog is now only displayed when weather data for more than one tour is retrieved. 

You may customize this number when you implement a UI for it.
