### ISSUE TITLE
[Bug : Translation:AirQuality:German] 

### ISSUE THREAD

**Issue by Thompson-ongithub** [mytourbook/mytourbook#1124]
### What happened ?

The German translations of the Air Quality to me seem a bit buggy:
if I remember correctly it's good / fair / moderate / poor / very poor in English but Gut (_good_) / schön (_nice_) / moderat (_moderate_) / schlecht (_poor_) / sehr schlecht (_very poor_)

Instead of schön I'd suggest using mittelmäßig. So the choices would be _gut / mittelmäßig / ausreichend / schlecht / sehr schlecht_

### Version

23.5

### System

Linux

**Comment by wolfgang-ch** [comment]
I struggled with the translation of _nice_: **schön** because it' similar like _good_: **gut** 

What about using one of these translations?

I like the naming in the first picture

1.
![image](https://github.com/mytourbook/mytourbook/assets/1283445/3e482bd2-7842-4921-8ad8-3fd549b9c4f2)

2.
![image](https://github.com/mytourbook/mytourbook/assets/1283445/996230c2-1120-426d-be73-d9f9f35ac5d7)

3.
![image](https://github.com/mytourbook/mytourbook/assets/1283445/301f3c90-5baf-4b7b-b01c-e3bddecb00b1)

**Comment by Thompson-ongithub** [comment]
I took my naming suggestion from the second link (loveair.de) because I liked that better (but I suppose in the end it's down to personal preferences). The downside when using the naming of the first picture is that it's getting rather long...

**Comment by wolfgang-ch** [comment]
The wording is changed in the next version

![image](https://github.com/mytourbook/mytourbook/assets/1283445/d13e953d-3302-41b7-a9ab-180fe7d9870d)
