### ISSUE TITLE
[Fit export/import] Different values reimporting and exported activity

### ISSUE THREAD

**Issue by mff73** [mytourbook/mytourbook#1135]
### What happened ?

Export a tour into a fit file (with pauses) and reimport it in MTB (same file) and time values are not the same :(

![image](https://github.com/mytourbook/mytourbook/assets/50132146/e11c2401-5f1f-48be-8767-d8e9c6195b92)

on the right an activity with 2 pauses, export a fit file from it, and on the left, reimporting step shows different time (8:16:33 instead of 7;30:22)

to be transparent, initial tour is a concatenated tour from two other tours i deleted, not sure it is linked, but who knows.
here are original two tours fit files to check

[2023-06-10T08-02-tours.zip](https://github.com/mytourbook/mytourbook/files/11837778/2023-06-10T08-02-tours.zip)

### Version

23.5

### System

Windows

**Comment by FJBDev** [comment]
@mff73 

Your issue is confusing.

>reimporting step shows different time (8:16:33 instead of 7;30:22)

One is **moving time** (8:16:33) and the other one is **recorded time** (7:30:22). Given that the moving time is computed with an algorithm and that the recorded time = Elapsed Time - Paused Time, this could be normal that they are different. (see more info on all the time definition in MT [here](https://mytourbook.sourceforge.io/mytourbook/index.php/history/history-2020#v20.11.0))
I think you should compare "apples with apples" and therefore compare `moving time` with `moving time` and `recorded time` with `recorded time`.

![image](https://github.com/mytourbook/mytourbook/assets/25235665/c9ee5f03-a2e5-43f8-a02f-38dbfb3c88a0)


If you look at your screenshot and read the Elapsed time values (8:21:17), they are both identical

**Comment by mff73** [comment]
@FJBDev 
i am effectively stupid :(
Sorry, I saw two time values, without looking at their definitions (and i agree to compare now apples to apples :) )

But, and maybe it is discussed somewhere else i have not searched  : how is it possible to have Moving Time superior to Recorded Time ? Could we be considered as moving while recording is "paused" ?
