### ISSUE TITLE
[Bug : Slideouts] The drop down menus in slideouts are immediately disappearing when selected

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1142]
### What happened ?

See the video below that shows how to reproduce the issue:

(I thought I had created an issue 2-3 years ago (you can see the video is using 20.3.0) but I can't find it 

[Untitled Project.webm](https://github.com/mytourbook/mytourbook/assets/25235665/8b573dd7-d90d-448e-86ee-82a6ed1512cf)

### Version

23.5.1

### System

Linux

**Comment by wolfgang-ch** [comment]
This issue is "solved" by using listboxes but I know on Linix this is an issue.

A workaround for dropdown boxes is to **not** select the dropdown box, just move the mouse over the dropbox and select an item with the mouse wheel that the dropdown box is not opened. When a dropdown box is opened (this is another window) then the slideout is loosing the focus and closes. As I remember it's difficult (or impossible) to put some code into somewhere, when a dropdown box opens/closes.

For the color dialog there is a workaround implemented that the slidout is not closing when the color dialog open

![image](https://github.com/mytourbook/mytourbook/assets/1283445/a2b39100-7dcc-4f1c-ba97-2b4d409ed9c6)

**Comment by FJBDev** [comment]
> A workaround for dropdown boxes is to **not** select the dropdown box, just move the mouse over the dropbox and select an item with the mouse wheel that the dropdown box is not opened.


The workaround/hack works but it's not intuitive for the user

**Comment by wolfgang-ch** [comment]
There are in several places `keepOpenListeners` which do not close the slideout when the combobox has the focus

![image](https://github.com/mytourbook/mytourbook/assets/1283445/7e28f5bc-c800-42ea-bb03-84b571f70df5)

but the focus with the tab key do very often not work in slideouts

**Comment by wolfgang-ch** [comment]
There is no know method to fix this issue
