### ISSUE TITLE
[Bug : Tour Data] 

### ISSUE THREAD

**Issue by stvzldn** [mytourbook/mytourbook#1189]
### What happened ?

The Tour Data does not respond to the mouse scroll wheel nor to PageUp/PageDown nor Up/Down arrow.
If I mouse click on the first line of the Tour Data (i.e. the "C" of Created), then I get a single mouse wheel scroll or a PageDown.  After that all mouse is ignored.
I can use the mouse to LeftClick and drag the scroll bar to any line of the Tour Data window.  I find this is the only way to see all Tour Data. I can always copy to clipboard and view with an editor as a workaround.

### Version

23.8.0 and prior

### System

Windows

**Comment by wolfgang-ch** [comment]
I'm aware of this limitation since 4 years but this is the reason, see line 117

https://github.com/mytourbook/mytourbook/blob/ba816632da53b31c44f036a35e19a6de5b15a9ad/bundles/net.tourbook/src/net/tourbook/ui/views/TourDataView.java#L116-L121

A text field with scrollbars could be used (currently a text field without scrollbars is used) but it would look really ugly when there are two scrollbars on the right side of this view.

**There is a workaround, move the mouse over the scrollbar, then the mousewheel works and the content can be scrolled to the bottom**


https://github.com/mytourbook/mytourbook/assets/1283445/96808582-b9b7-4c07-8524-ef0c07e471f5

**Comment by wolfgang-ch** [comment]
After thinking more about this issue, I found a solution to scroll the fields with the mouse wheel, page up/down or cursor up/down. 

This will be available in the next version https://github.com/mytourbook/mytourbook/commit/b2fc15b7d5e3bd62d01cfdaac6363f4c135ce46b
