### ISSUE TITLE
[Feature : Tour Editor] Improve Autocomplete Fields

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1199]
### What is missing ?

The popup of the autocomplete fields can be resized since ever (which I discovered just now) but it do not keep the popup height when the tour editor is reopened.

Improvements in this feature:
* Increased default height
* Keep popup height when editor is reopened

https://github.com/mytourbook/mytourbook/assets/1283445/044512eb-ff8a-4258-8422-d81341128a93

**Comment by wolfgang-ch** [comment]
Implemented in https://github.com/mytourbook/mytourbook/commit/263017a4d224a4a95cedd018dbbab3d95cd71712

**Comment by Thompson-ongithub** [comment]
It took me a while (actually until a found this closed issue) until I realized that the Autocomplete Fields now (not sure about 23.08, I never really used it, but at least in 20.10 Beta 1) because strangely in 20.10 Beta 1 they didn't open like before right underneath the field they were associated to but in the top right corner of the window (at least with Start/End location, didn't pay as much attention to the title)
(Linux, 20.10 Beta 1)
After having changed the height once they behave as they should (i.e. start right underneath the field). I  just need to get used to the fact that by now they use the width of the text field as they weren't as wide before...

**Comment by wolfgang-ch** [comment]
I didn't changed the location of the popup dialog, only the height is now set to the previous value when this popup dialog is reopened
