### ISSUE TITLE
[Bug : Color Selector] : Basic colors not showing (after once having done so)

### ISSUE THREAD

**Issue by Thompson-ongithub** [mytourbook/mytourbook#1208]
### What happened ?

After once having shown Basic and custom colors, MTB in Linux only shows 8 custom colors. A restart of MTB hasn't helped.

![MTB_Colour-selection](https://github.com/mytourbook/mytourbook/assets/127450598/22092bd6-d41a-4c30-a503-e7a5f4d6515c)

### Version

23.10 Beta + Beta 2

### System

Linux

**Comment by wolfgang-ch** [comment]
This feature is now disabled for Linux because the Linux color selector already displays the last custom colors.

![image](https://github.com/mytourbook/mytourbook/assets/1283445/63264cbe-0376-4e6e-92ea-6d2497161d70)

![image](https://github.com/mytourbook/mytourbook/assets/1283445/b0767f9f-8bfb-45fa-b803-59def6d93b94)
