### ISSUE TITLE
[Pref Person] Wrong person height when using imperial

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1255]
### Discussed in https://github.com/mytourbook/mytourbook/discussions/1254

<div type='discussions-op-text'>

<sup>Originally posted by **stvzldn** January 13, 2024</sup>
Person height using the Imperial measurement (not tested for Metric) is overstated in the People List by 1 or 2 inches over the Person dialog box.
![Image1](https://github.com/mytourbook/mytourbook/assets/106929478/e0c9fd26-7ff6-490d-98b5-5a011981b6f5)
</div>

**Comment by wolfgang-ch** [comment]
I think it's a rounding issue because internally all is computed in metric

**Comment by wolfgang-ch** [comment]
This is fixed in 24.1

**Comment by FJBDev** [comment]
> This is fixed in 24.1

I just realized that this bugfix is breaking the unit tests but actually the unit tests were already showing this bug !
I didn't realize at the time, but the unit tests should have shown that since a different BMI was computed using the same person height in different measurement systems.

I have a [commit ](https://github.com/FJBDev/mytourbook/pull/164/commits/20290dd9e3b7f7639aa72a92b3dd8b44996e1251)to fix that in my next PR where I am translating the 24.1 french texts

**Comment by wolfgang-ch** [comment]
>I didn't realize at the time, but the unit tests should have highlighted this bug since a different BMI was computed using the same person height in different measurement systems.

You need a unit test to test the unit tests 😄
