### ISSUE TITLE
[Feature : Tour Tags Grouping] 

### ISSUE THREAD

**Issue by kiludi** [mytourbook/mytourbook#1358]
### Tour Tags Grouping

Hi,
I use a lot the tags in all my tours to tack the usage of my bikes and the different components.
Is there any way to group the tags with one bike and its components and assign this group directly to a tour?
This will save time when uploading the tours as I have several components in my bikes.
Also is there any way to create default tags to be added by default to new activities?
Thank you in advance for your answer

**Comment by wolfgang-ch** [comment]
> Is there any way to group the tags with one bike and its components and assign this group directly to a tour?

No, there is currently not tag grouping, there is only a tour type grouping

> Also is there any way to create default tags to be added by default to new activities?

No but the easy import could be extended with this feature

**Comment by bern6** [comment]
This future feature might interest you "1301" copy/paste tour tags

**Comment by kiludi** [comment]
> No but the easy import could be extended with this feature
That would be very good

**Comment by kiludi** [comment]
> This future feature might interest you "1301" copy/paste tour tags

Yes. Very interesting.
Should I do anything?

**Comment by cyc1ingsir** [comment]
> usage of my bikes and the different components
Oh, I'm pleased to hear that I'm not the only one doing this. :smile: 
There feature #777 is a place, where we had a discussion about this.

I myself are not using the tags, found it easier to stick to tour types.
However, I recently duplicated quite a few tour types since each of the type, I've defined, is tied to one bike only, but containing two information. Like roadbike-training, gravelbike-training, roadbike-groupride, gravel... . This enables me to differentiate between the bikes used for each tour. 
I would love to see the option for referencing a tour to a certain bike. Having just had a look at the tags, I see, that I could use the tags for this but somehow would prefer to make the referencing more explicit.

I recently learned that a mate of mine is tracking the usage of it's components as well. He started - as a Garmin Edge user - using Garmin Connect(?) and changed to Strava (a Pro option?) for doing so later on.

I'm still using my local hosted prototype being fed with MyTourbook DB exports for component tracking but my tracker could do with a few UX improvements :blush: .

**Comment by FJBDev** [comment]
> > usage of my bikes and the different components
> 
> Oh, I'm pleased to hear that I'm not the only one doing this. 😄 The feature #777 is a place, where we had a discussion about this.


This is exactly what I thought when I saw this issue. The feature #777 would be perfect !

If anyone is interested in contributing to MT, feel free to look into that feature, it would be a VERY nice addition to MT!

**Comment by wolfgang-ch** [comment]
Parts of the requested feature will be available in the next version

Don't be confused with the random tag names, the same tag in different tours is displayed randomly

https://github.com/user-attachments/assets/6354a3b1-d51f-47c8-a68f-c89771a18851

**Comment by wolfgang-ch** [comment]
> Also is there any way to create default tags to be added by default to new activities?

How should default tags be identified?

**Comment by kiludi** [comment]
> Parts of the requested feature will be available in the next version
> 
> Don't be confused with the random tag names, the same tag in different tours is displayed randomly
> 
>  mt-grouped-tags.mp4

That's great!!.
Thank you very much.
I am looking forward for the next update!

**Comment by kiludi** [comment]
> > Also is there any way to create default tags to be added by default to new activities?
> 
> How should default tags be identified?

For example, in your video you have a group named "Hund".
What I mean, is that I should be able to put somewhere this as a defalut group for new actvities, and later change it only of needed because I have used another bike.
But this is a very minor point.

**Comment by wolfgang-ch** [comment]
Tags can now be set with easy import

There will be no default tag group, each easy import tile can have a different tag group

![image](https://github.com/user-attachments/assets/cc5dcbe7-60b8-47dd-9c7e-60a85575b489)

![image](https://github.com/user-attachments/assets/b949ec01-26c8-46d5-8722-77013fed0ee8)
