### ISSUE TITLE
[Bug : TCX Import] Some tour pauses are wrong

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1370]
### What happened ?

While playing with the new pause feature in the 2D map, I saw that some pauses are not displayed and after analyzing the data, there are pauses which do not exist.

The first pause is OK, but not the second and third and some pauses are not recognized.

![image](https://github.com/mytourbook/mytourbook/assets/1283445/2487c142-87bb-476d-95e5-a4ac75615281)

[2009-03-06-13-52-08-truncated.zip](https://github.com/user-attachments/files/15929422/2009-03-06-13-52-08-truncated.zip)

### Version

24.7

### System

All

**Comment by FJBDev** [comment]
I am not surprised that there is a bug when importing the pauses from a TCX file because, like other users, I have not found official documentation and clear explanation on how the TCX pauses are represented and therefore had to do some guessing.

[Here ](https://stackoverflow.com/questions/27050144/in-the-tcx-format-how-is-a-trackpoint-marked-as-paused)you can find where I and other people shared our struggles and what I had found at the time

**Comment by wolfgang-ch** [comment]
I will implement an option to use the break times instead of the guessed paused time. I used part of your comment in this dialog 😄 

![image](https://github.com/mytourbook/mytourbook/assets/1283445/d3dae47e-43ed-47f7-8490-3cad29c467d3)
