### ISSUE TITLE
[Weather] Add "WeatherApi" provider

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#505]
Add the ["WeatherApi"](https://www.weatherapi.com) weather provider that offers a free 7-day historical weather retrieval

[Source](https://www.weatherapi.com/pricing.aspx)
![image](https://user-images.githubusercontent.com/25235665/161605697-f8a241ec-2d10-4b18-b28f-1bd2abcf764b.png)

**Comment by wolfgang-ch** [comment]
There is a big difference in the weather data between WeatherAPI and OpenWeatherMap.

In this tour the average temperature was around 20° Celcius and not around 27° C. It would be very interresting to know, from which location are the weather data

![image](https://user-images.githubusercontent.com/1283445/171796441-b6bbf797-bda1-4bd3-91d4-2dfef77512d6.png)

The temperature peak at the beginning is because it was very steep and sunny, later on there were more shadow because of the clouds/forest

![image](https://user-images.githubusercontent.com/1283445/171797768-c3ff5957-1cd0-4c10-bbaa-8122e8eb5d7d.png)

Maybe both free weather data could be retrieved and saved in the log

**Comment by FJBDev** [comment]
> There is a big difference in the weather data between WeatherAPI and OpenWeatherMap.
>  It would be very interresting to know, from which location are the weather data

I have seen differences like this too. WWO shows the weather station with a clickable web link but not OpenWeatherMap or WeatherAPI

![image](https://user-images.githubusercontent.com/25235665/171874807-171f490b-af8a-4b29-b1e2-4a7e966f0f6f.png)
