### ISSUE TITLE
[FeatureFromSF] Add photos to tags

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#805]
Since I'm using tags for equipment (shoes, mostly, but also other gear), it would be cool to have a photo of the gear with the tag. I'm spoiled by this feature in ST3: nice to see the little icon for the device I'm looking for as well as the description. 

Ideally, this photo would be tied in the tag from the "Edit tag" feature and would be able to display in views and selection of tags as well. 

Reported by: gregoryx

Original Ticket: [mytourbook/feature-requests/153](https://sourceforge.net/p/mytourbook/feature-requests/153)

**Comment by FJBDev** [comment]
Here is a preview of this requested feature:

- The "Edit Tag" contains a button to upload an image that MT will resize to 70x70 pixels for an optimum display and space savings. We could discuss 100x100 or 50x50 etc...
![image](https://user-images.githubusercontent.com/25235665/202572393-a8afb8a9-b5e4-499b-8aa0-a6331c21bfd4.png)


- The Tour Data Editor View would contain the list of tags with their image and name.

![image](https://user-images.githubusercontent.com/25235665/202572594-f5539c92-ebd0-463f-82da-1ddd577fb2f5.png)


Thoughts ?

I've added @mff73, @stvzldn, @Yannos60 because I know they are/were ST3.1 users and might have suggestions, critics....

**Comment by stvzldn** [comment]
I would love to have a way to designate a tag as having an "accumulation" property so the tag item could accumulate frequency or time or distance when attached to a tour.  Then have a field in the tag structure displaying the property and its value.

**Comment by FJBDev** [comment]
Not sure to understand the "accumulation" property. You mean displaying the total hours/miles used below the name ?

**Comment by stvzldn** [comment]
Yes

**Comment by FJBDev** [comment]
> Yes

Ok, I will look into that. I think it should be possible

**Comment by FJBDev** [comment]
> I would love to have a way to designate a tag as having an "accumulation" property so the tag item could accumulate frequency or time or distance when attached to a tour. Then have a field in the tag structure displaying the property and its value.

How does that look for displaying the "accumulation" properties ?

![image](https://user-images.githubusercontent.com/25235665/202759197-20a0007a-ec3e-43bf-9cf5-549e2f8ed8c0.png)

**Comment by stvzldn** [comment]
Very nice display

**Comment by wolfgang-ch** [comment]
Pictures tell more than text

but the squeezed shoe looks a bit ugly

![image](https://user-images.githubusercontent.com/1283445/202836507-1f05cdc9-8025-4ae3-9fa9-d9072f28119f.png)

**Comment by FJBDev** [comment]
> Pictures tell more than text
> 
> but the squeezed shoe looks a bit ugly
> 
This image is squeezed because as I said above ` MT will resize to 70x70 pixel` and because the picture was not a square in the first place and I didn't want to crop it, it squeezed it. Of course, I am open to suggestions

**Comment by wolfgang-ch** [comment]
`ImageCanvas` takes care about the image ratio

https://github.com/mytourbook/mytourbook/blob/43ff8a2d4f5f9d968dbec4c6f36f1fde428a29ac/bundles/net.tourbook.common/src/net/tourbook/common/widgets/ImageCanvas.java#L211-L248

**Comment by FJBDev** [comment]
> `ImageCanvas` takes care about the image ratio
>

So would it be best to store each image in MT's database with the original ratio and have an upper limit of 70pixels for either the width or height ? (for example 70x58 or 43x70 ?)

**Comment by wolfgang-ch** [comment]
I would not save any media resources in the database, only the absolute/relative path and other metadata when needed, like in `net.tourbook.data.TourPhoto`

**Comment by FJBDev** [comment]
> I would not save any media resources in the tour database, only the absolute/relative path and other metadata when needed, like in `net.tourbook.data.TourPhoto`
> 
> When I would have to save media resouces in a database then I would use a separate database.

An image of 70pixels is only 3KB, it's not possible to save that in the DB ??
![image](https://user-images.githubusercontent.com/25235665/203105169-25005175-fa6e-44af-9451-634d0c305953.png)

I can redo my code and not save images but use a file path.
Any other requirements I should know for this feature request so I don't do lots of code that needs to be discarded in the end ?

**Comment by wolfgang-ch** [comment]
>An image of 70pixels is only 3KB, it's not possible to save that in the DB ??

What I don't understand is why you want to save/read images from the database and on the other site, about 900 icon images are already loaded from the file system?

> Any other requirements I should know for this feature request so I don't do lots of code that needs to be discarded in the end ?

I've not yet thought in details about this feature but are the tag images static images or can the user select the image from the file system?

I know that creating program code with images can be very time consuming, it took me about one year to implement the photo feature in MT.

You also have to take care about disposing images when they are not needed but the sleak tool https://www.eclipse.org/swt/tools.php can find the leaked images.

**Comment by FJBDev** [comment]
> What I don't understand is why you want to save/read images from the database and on the other site, about 900 icon images are already loaded from the file system?

Because what the users are asking is to display an image for each of their tags. Example: Bike, running shoe, backpack etc.....
I could display from a local file, i just thought that a small 70x70 image (as a `byte[]`) could easily being save in the DB. But loading it from a local file could work too.

> I've not yet thought in details about this feature but are the tag images static images or can the user select the image from the file system?
> 
> I know that creating program code with images can be very time consuming, it took me about one year to implement the photo feature in MT.
> 
> You also have to take care about disposing images when they are not needed but the sleak tool https://www.eclipse.org/swt/tools.php can find the leaked images.

This feature is actually not really complicated as it consists of displaying an image for each given tag. And indeed disposing each image was a TODO on my list of things for this feature

**Comment by wolfgang-ch** [comment]
> And indeed disposing each image was a TODO on my list of things for this feature

For images which are used at several places in the app, e.g. graph image for elevation, it is difficult to dispose them, for these images there is an image registry `net.tourbook.ui.UI.IMAGE_REGISTRY`

**Comment by wolfgang-ch** [comment]
There is a max number of available image handles (which depends on the OS), so in the image registry not every images should be kept.

![image](https://user-images.githubusercontent.com/1283445/203236951-000e1919-44ba-424e-846f-1aab47f76073.png)

**Comment by cyc1ingsir** [comment]
> How does that look for displaying the "accumulation" properties ?

With this feature being implemented, I would be able to track used hours and mileage of equipment, right?

That's something, I'd be very interested in and have thought about within the last months.

However, what I'm after is to track quite a few things, especially equipment/parts I'm swapping sometimes from ride to ride (wheel sets, front or rear wheel only, rims, ...) or equipment I'm using for a certain period of time (different chain rings whilst going for a cycling holiday in the Alps.) or just parts needing replacement at a certain time (brake pads and discs, chain, ...),
This becomes a long list containing quite a few items I would have to remember setting the tags for after each tour.

If I think about it, it's a growing list containing almost every part of the bicycle. e.g. Just having had to a replace a broken front derailleur on the last holiday which I now having received back repaired from the manufacturer ready for a new life on the bike.
I'm not sure, this feature request is targeting this use case too.
The thing is. MTB is my central tool for tracking all my cycling activity. If I want to know my mileage done with, the hours spent on my bike, I always looking it up on MTB.
To easily track the equipments/parts data (mileage, hours) the possibility to define the bike's composition at any given time and being able to assign this bike to the tour would be probably best.
I'm not sure if this would be still the scope of _My_TourBook since it's not called My_Equipments_TourBook. But maybe it's not only me having this use case, or one has even come up with an easy solution to this.
Even though, this being integrated within MBT I would like the most.

**Comment by FJBDev** [comment]
> With this feature being implemented, I would be able to track used hours and mileage of equipment, right?
> 

You can already do that as of today, at least I have been since I first used MT back in 2016-2017. Unless I am misunderstanding something ?

> That's something, I'd be very interested in and have thought about within the last months.
> 
> However, what I'm after is to track quite a few things, especially equipment/parts I'm swapping sometimes from ride to ride (wheel sets, front or rear wheel only, rims, ...) or equipment I'm using for a certain period of time (different chain rings whilst going for a cycling holiday in the Alps.) or just parts needing replacement at a certain time (brake pads and discs, chain, ...), This becomes a long list containing quite a few items I would have to remember setting the tags for after each tour.

That is a different scope than this feature request though. Can you create a separate feature request ?

**Comment by FJBDev** [comment]
> > That's something, I'd be very interested in and have thought about within the last months.
> > However, what I'm after is to track quite a few things, especially equipment/parts I'm swapping sometimes from ride to ride (wheel sets, front or rear wheel only, rims, ...) or equipment I'm using for a certain period of time (different chain rings whilst going for a cycling holiday in the Alps.) or just parts needing replacement at a certain time (brake pads and discs, chain, ...), This becomes a long list containing quite a few items I would have to remember setting the tags for after each tour.
> 
> That is a different scope than this feature request though. Can you create a separate feature request ?

Actually, is that what you meant ? [Personal/Mechanical performance and bike maintenance
](https://github.com/mytourbook/mytourbook/issues/777)

**Comment by FJBDev** [comment]
Feature implemented as below:

- For each tag, an image file path can be linked (the image is not saved in the database of MT)

![image](https://user-images.githubusercontent.com/25235665/218219558-8e656ec4-d43e-44d5-902a-2429e0a80fd5.png)


- The image will be displayed in the Tour Data Editor View with the accumulated values of the tag (time and distance used)

![image](https://user-images.githubusercontent.com/25235665/218219426-cc601fec-1d72-4d89-baf5-42d681ffbd91.png)


- The image will be displayed in the tour contextual menu

![image](https://user-images.githubusercontent.com/25235665/218219511-182e6178-e505-4aad-b2bb-2102271c9a5b.png)

**Comment by FJBDev** [comment]
> Pictures tell more than text
> 
> but the squeezed shoe looks a bit ugly
> 
> ![image](https://user-images.githubusercontent.com/1283445/202836507-1f05cdc9-8025-4ae3-9fa9-d9072f28119f.png)

Now it should not be ugly/squeezed anymore as I have changed the resizing to be proportional to the original image's dimensions

![image](https://user-images.githubusercontent.com/25235665/218220856-bf69eeef-7ab7-46c6-aefb-ff900da66c0d.png)

**Comment by FJBDev** [comment]
This feature was merged today in `main` and will be available in MT 23.3

![image](https://user-images.githubusercontent.com/25235665/220996048-4c0b2b0d-ee71-4f82-8bad-178310c5d7f4.png)

![image](https://user-images.githubusercontent.com/25235665/220996178-cb860c62-e070-41af-a0cc-7c98676d7c35.png)
